name: 'Ordino Test Runner'
description: 'Run Ordino tests with Cypress or Playwright, with automatic sharding and report upload to Ordino dashboard'
author: 'Ordino'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  # Test Framework Selection
  test-framework:
    description: 'Testing framework to use (cypress or playwright)'
    required: true
    default: 'cypress'
  
  # Action Mode
  action-mode:
    description: 'Action mode: test (run tests) or merge-and-upload (merge reports and upload)'
    required: false
    default: 'test'
  
  # Sharding Configuration
  total-shards:
    description: 'Total number of parallel shards'
    required: false
    default: '1'
  
  shard-index:
    description: 'Current shard index (1-based for Playwright compatibility)'
    required: false
    default: '1'
  
  # Commands
  initialize-command:
    description: 'Command to initialize the project'
    required: false
    default: 'npm run initialize'
  
  test-command:
    description: 'Command to run tests (without shard arguments)'
    required: false
    default: 'npm run oi:run:test'
  
  # Configuration
  ordino-url:
    description: 'Ordino API URL'
    required: false
    default: 'https://dev-portal.ordino.ai'
  
  working-directory:
    description: 'Working directory for the tests'
    required: false
    default: '.'
  
  config-file:
    description: 'Cypress configuration file (cypress only)'
    required: false
    default: 'ordino.config.ts'
  
  install-playwright-browsers:
    description: 'Install Playwright browsers'
    required: false
    default: 'true'
  
  # Credentials
  ordino-key:
    description: 'Ordino API key (can also be set via ORDINO_KEY env or .env file)'
    required: false
  
  project-id:
    description: 'Project ID for Ordino (can also be set via PROJECT_ID env or .env file)'
    required: false
  
  use-env-file:
    description: 'Use .env file for credentials if not provided'
    required: false
    default: 'true'
  
  # Control Options
  skip-upload:
    description: 'Skip uploading results to Ordino dashboard'
    required: false
    default: 'false'
  
  continue-on-error:
    description: 'Continue workflow even if tests fail'
    required: false
    default: 'true'
  
  # For merge-and-upload mode
  reports-directory:
    description: 'Directory containing downloaded shard reports (for merge-and-upload mode)'
    required: false
    default: 'all-reports'

outputs:
  test-results-path:
    description: 'Path to test results file'
    value: ${{ steps.prepare-report.outputs.report-path }}
  
  tests-passed:
    description: 'Whether all tests passed'
    value: ${{ steps.run-tests.outputs.tests-passed }}
  
  report-uploaded:
    description: 'Whether the report was successfully uploaded'
    value: ${{ steps.upload-report.outputs.success }}
  
  ordino-dashboard-url:
    description: 'URL to view results in Ordino dashboard'
    value: ${{ steps.upload-report.outputs.dashboard-url }}

runs:
  using: "composite"
  steps:
    # Step 0: Install Required Tools (for Alpine containers)
    - name: Setup Container Environment
      shell: sh
      run: |
        echo "🔧 Setting up container environment..."
        
        # Detect if we're in Alpine Linux
        if [ -f /etc/alpine-release ]; then
          echo "Detected Alpine Linux container"
          if ! command -v bash >/dev/null 2>&1; then
            echo "Installing bash..."
            apk add --no-cache bash
          fi
          if ! command -v curl >/dev/null 2>&1; then
            echo "Installing curl..."
            apk add --no-cache curl
          fi
          if ! command -v node >/dev/null 2>&1; then
            echo "Installing Node.js..."
            apk add --no-cache nodejs npm
          fi
        fi
        
        # Detect if we're in Debian/Ubuntu
        if [ -f /etc/debian_version ]; then
          echo "Detected Debian/Ubuntu container"
          if ! command -v curl >/dev/null 2>&1; then
            echo "Installing curl..."
            apt-get update && apt-get install -y curl
          fi
        fi
    
    # Step 1: Setup Environment
    - name: Setup Environment
      id: setup
      shell: bash
      run: |
        echo "🚀 Setting up Ordino Test Runner"
        echo "Mode: ${{ inputs.action-mode }}"
        echo "Framework: ${{ inputs.test-framework }}"
        echo "Total Shards: ${{ inputs.total-shards }}"
        echo "Current Shard: ${{ inputs.shard-index }}"
        echo "Working Directory: ${{ inputs.working-directory }}"
        
        # Validate framework selection
        if [[ "${{ inputs.test-framework }}" != "cypress" && "${{ inputs.test-framework }}" != "playwright" ]]; then
          echo "❌ Error: test-framework must be either 'cypress' or 'playwright'"
          exit 1
        fi
    
    # Step 2: Load Credentials
    - name: Load Credentials
      id: load-credentials
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Priority: Input parameters > Environment variables > .env file
        ORDINO_KEY="${{ inputs.ordino-key }}"
        PROJECT_ID="${{ inputs.project-id }}"
        
        # Try environment variables if inputs are empty
        if [ -z "$ORDINO_KEY" ]; then
          ORDINO_KEY="${ORDINO_KEY:-${{ env.ORDINO_KEY }}}"
        fi
        if [ -z "$PROJECT_ID" ]; then
          PROJECT_ID="${PROJECT_ID:-${{ env.PROJECT_ID }}}"
        fi
        
        # Try .env file if still empty and use-env-file is true
        if [[ "${{ inputs.use-env-file }}" == "true" ]] && [[ -z "$ORDINO_KEY" || -z "$PROJECT_ID" ]]; then
          if [ -f ".env" ]; then
            echo "📁 Loading credentials from .env file..."
            set -a
            source .env
            set +a
          elif [ -f "/root/.env" ]; then
            echo "📁 Loading credentials from /root/.env file..."
            set -a
            source /root/.env
            set +a
          fi
        fi
        
        # Mask and output credentials
        if [ -n "$ORDINO_KEY" ]; then
          echo "::add-mask::$ORDINO_KEY"
          echo "ordino-key=$ORDINO_KEY" >> $GITHUB_OUTPUT
          echo "✅ ORDINO_KEY loaded"
        else
          echo "⚠️ Warning: ORDINO_KEY not found"
        fi
        
        if [ -n "$PROJECT_ID" ]; then
          echo "::add-mask::$PROJECT_ID"
          echo "project-id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "✅ PROJECT_ID loaded"
        else
          echo "⚠️ Warning: PROJECT_ID not found"
        fi
        
        # Only fail if we're not skipping upload
        if [[ "${{ inputs.skip-upload }}" == "false" ]] && [[ -z "$ORDINO_KEY" || -z "$PROJECT_ID" ]]; then
          echo "❌ Error: ORDINO_KEY and PROJECT_ID are required for uploading results"
          exit 1
        fi
    
    # Step 3: Cache Dependencies (only for test mode)
    - name: Cache Dependencies
      if: ${{ inputs.action-mode == 'test' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache
          ${{ inputs.working-directory }}/node_modules
        key: ordino-${{ inputs.test-framework }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ordino-${{ inputs.test-framework }}-${{ runner.os }}-
    
    # Step 4: Install Dependencies (only for test mode)
    - name: Install Dependencies
      if: ${{ inputs.action-mode == 'test' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ORDINO_KEY: ${{ steps.load-credentials.outputs.ordino-key }}
      run: |
        echo "📦 Installing dependencies..."
        
        # Try the initialize command
        if ! ${{ inputs.initialize-command }} --legacy-peer-deps --omit=optional; then
          echo "Initialize command failed, trying without flags..."
          ${{ inputs.initialize-command }}
        fi
        
        # Install Playwright browsers if needed
        if [[ "${{ inputs.test-framework }}" == "playwright" ]] && [[ "${{ inputs.install-playwright-browsers }}" == "true" ]]; then
          echo "🎭 Installing Playwright browsers..."
          if [ -f /etc/alpine-release ]; then
            echo "⚠️ Warning: Alpine Linux detected. Installing additional dependencies..."
            apk add --no-cache chromium nss freetype freetype-dev harfbuzz ca-certificates ttf-freefont
          fi
          
          if command -v npx &> /dev/null; then
            npx playwright install chromium || true
            npx playwright install-deps chromium || true
          fi
        fi
    
    # Step 5: Run Tests (only for test mode - WITH SHARDING SUPPORT)
    - name: Run Tests
      id: run-tests
      if: ${{ inputs.action-mode == 'test' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ORDINO_KEY: ${{ steps.load-credentials.outputs.ordino-key }}
        TEST_FRAMEWORK: ${{ inputs.test-framework }}
      run: |
        echo "🧪 Running ${{ inputs.test-framework }} tests..."
        
        # Create report directory
        mkdir -p ordino-report
        
        # Set test exit code variable
        TEST_EXIT_CODE=0
        
        # Run tests based on framework
        if [[ "${{ inputs.test-framework }}" == "cypress" ]]; then
          echo "Running Cypress tests..."
          mkdir -p ordino-report/report
          
          # Run with Cypress sharding if needed
          if [[ "${{ inputs.total-shards }}" -gt "1" ]]; then
            CYPRESS_SHARD_INDEX=$(({{ inputs.shard-index }} - 1))
            export SPLIT="${{ inputs.total-shards }}"
            export SPLIT_INDEX="$CYPRESS_SHARD_INDEX"
            echo "Running with SPLIT=$SPLIT SPLIT_INDEX=$SPLIT_INDEX"
          fi
          
          if ${{ inputs.test-command }}; then
            echo "✅ Tests completed successfully"
          else
            TEST_EXIT_CODE=$?
            echo "⚠️ Tests completed with exit code: $TEST_EXIT_CODE"
          fi
        else
          echo "Running Playwright tests..."
          mkdir -p ordino-report/mochawesome
          
          # Run with Playwright sharding if needed
          if [[ "${{ inputs.total-shards }}" -gt "1" ]]; then
            echo "Running shard ${{ inputs.shard-index }} of ${{ inputs.total-shards }}"
            TEST_CMD="${{ inputs.test-command }} -- --shard=${{ inputs.shard-index }}/${{ inputs.total-shards }}"
            echo "Running command: $TEST_CMD"
            
            if eval "$TEST_CMD"; then
              echo "✅ Tests completed successfully"
            else
              TEST_EXIT_CODE=$?
              echo "⚠️ Tests completed with exit code: $TEST_EXIT_CODE"
            fi
          else
            # No sharding
            if ${{ inputs.test-command }}; then
              echo "✅ Tests completed successfully"
            else
              TEST_EXIT_CODE=$?
              echo "⚠️ Tests completed with exit code: $TEST_EXIT_CODE"
            fi
          fi
        fi
        
        # Set output based on test results
        if [ $TEST_EXIT_CODE -eq 0 ]; then
          echo "tests-passed=true" >> $GITHUB_OUTPUT
        else
          echo "tests-passed=false" >> $GITHUB_OUTPUT
          if [[ "${{ inputs.continue-on-error }}" == "false" ]]; then
            exit $TEST_EXIT_CODE
          fi
        fi
    
    # Step 6: Merge Reports (for merge-and-upload mode - HANDLES PLAYWRIGHT MERGE)
    - name: Merge Parallel Reports
      id: merge-reports
      if: ${{ inputs.action-mode == 'merge-and-upload' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "📊 Merging reports from parallel execution..."
        
        if [[ "${{ inputs.test-framework }}" == "cypress" ]]; then
          # Cypress: Use mochawesome-merge
          echo "Merging Cypress reports..."
          mkdir -p ordino-report/report
          
          # Copy all Cypress reports from downloaded artifacts
          for report_dir in ${{ inputs.reports-directory }}/*/; do
            if [ -d "$report_dir/report" ]; then
              cp "$report_dir"/report/*.json ordino-report/report/ 2>/dev/null || true
            fi
          done
          
          # Merge using mochawesome-merge
          if ls ordino-report/report/*.json 1> /dev/null 2>&1; then
            npx mochawesome-merge "ordino-report/report/*.json" > ordino-report/final-report.json
            echo "✅ Successfully merged Cypress reports"
            echo "report-path=ordino-report/final-report.json" >> $GITHUB_OUTPUT
          else
            echo "❌ No Cypress reports found to merge"
            exit 1
          fi
        else
          # Playwright: Use the existing merge-reports.js from the framework
          echo "Merging Playwright reports..."
          mkdir -p ordino-report/mochawesome
          
          # Find and copy all mochawesome.json files
          shard_count=0
          for mochawesome_file in $(find ${{ inputs.reports-directory }} -name "mochawesome.json" -type f); do
            shard_count=$((shard_count + 1))
            cp "$mochawesome_file" "ordino-report/mochawesome/mochawesome-shard-$shard_count.json"
            echo "✅ Copied report from shard $shard_count"
          done
          
          if [ $shard_count -gt 0 ]; then
            echo "🔄 Using merge-reports.js to merge $shard_count reports..."
            
            if [ -f "merge-reports.js" ]; then
              node merge-reports.js
              
              if [ -f "ordino-report/mochawesome/mochawesome.json" ]; then
                echo "✅ Successfully merged $shard_count reports"
                echo "report-path=ordino-report/mochawesome/mochawesome.json" >> $GITHUB_OUTPUT
              else
                echo "❌ Failed to merge reports"
                exit 1
              fi
            else
              echo "❌ Error: merge-reports.js not found in repository!"
              exit 1
            fi
          else
            echo "❌ No mochawesome.json files found for merge"
            exit 1
          fi
        fi
    
    # Step 7: Prepare Report (for single execution only)
    - name: Prepare Test Report
      id: prepare-report
      if: ${{ inputs.action-mode == 'test' && inputs.total-shards == '1' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "📊 Preparing test report for single execution..."
        
        if [[ "${{ inputs.test-framework }}" == "cypress" ]]; then
          # Cypress report handling
          if ls ordino-report/report/*.json 1> /dev/null 2>&1; then
            if command -v npx &> /dev/null; then
              npx mochawesome-merge "ordino-report/report/*.json" > ordino-report/final-report.json || {
                echo "Failed to merge, using first report..."
                cp ordino-report/report/*.json ordino-report/final-report.json
              }
            else
              cp ordino-report/report/*.json ordino-report/final-report.json
            fi
            echo "report-path=ordino-report/final-report.json" >> $GITHUB_OUTPUT
          else
            echo "No Cypress reports found"
            echo "report-path=" >> $GITHUB_OUTPUT
          fi
        else
          # Playwright report handling
          if [ -f "ordino-report/mochawesome/mochawesome.json" ]; then
            echo "report-path=ordino-report/mochawesome/mochawesome.json" >> $GITHUB_OUTPUT
          else
            echo "No Playwright report found"
            echo "report-path=" >> $GITHUB_OUTPUT
          fi
        fi
    
    # Step 8: Upload Report to Ordino (UNIFIED FOR ALL SCENARIOS)
    - name: Upload Report to Ordino
      id: upload-report
      if: ${{ inputs.skip-upload == 'false' && (inputs.action-mode == 'merge-and-upload' || inputs.total-shards == '1') }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "☁️ Uploading report to Ordino dashboard..."
        
        API_URL="${{ inputs.ordino-url }}/api/v1/test-report-external"
        BUILD_ID="${GITHUB_RUN_ID}"
        PROJECT_ID="${{ steps.load-credentials.outputs.project-id }}"
        API_KEY="${{ steps.load-credentials.outputs.ordino-key }}"
        
        # Determine which report to upload
        if [[ "${{ inputs.action-mode }}" == "merge-and-upload" ]]; then
          REPORT_PATH="${{ steps.merge-reports.outputs.report-path }}"
        else
          REPORT_PATH="${{ steps.prepare-report.outputs.report-path }}"
        fi
        
        if [ -z "$REPORT_PATH" ] || [ ! -f "$REPORT_PATH" ]; then
          echo "❌ Error: No report file found to upload"
          echo "success=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        echo "Uploading report from: $REPORT_PATH"
        echo "File size: $(wc -c < "$REPORT_PATH") bytes"
        
        # Upload the report
        response=$(curl --location "$API_URL" \
          --header "Ordino-Key: $API_KEY" \
          --form "file=@$REPORT_PATH" \
          --form "ProjectId=$PROJECT_ID" \
          --form "ExecutionId=$BUILD_ID" \
          --write-out "%{http_code}" \
          --silent \
          --output response.json)
        
        if [ "$response" -eq 200 ] || [ "$response" -eq 201 ]; then
          echo "✅ Report uploaded successfully!"
          echo "success=true" >> $GITHUB_OUTPUT
          echo "dashboard-url=${{ inputs.ordino-url }}/dashboard/project/$PROJECT_ID/execution/$BUILD_ID" >> $GITHUB_OUTPUT
        else
          echo "❌ Failed to upload report. HTTP status: $response"
          if [ -f response.json ]; then
            cat response.json
          fi
          echo "success=false" >> $GITHUB_OUTPUT
          if [[ "${{ inputs.continue-on-error }}" == "false" ]]; then
            exit 1
          fi
        fi
    
    # Step 9: Summary
    - name: Generate Summary
      if: always()
      shell: bash
      run: |
        echo "## 📊 Ordino Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Mode**: ${{ inputs.action-mode }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Framework**: ${{ inputs.test-framework }}" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ inputs.action-mode }}" == "test" ]]; then
          if [[ "${{ inputs.total-shards }}" -gt "1" ]]; then
            echo "- **Shard**: ${{ inputs.shard-index }} of ${{ inputs.total-shards }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- **Tests Passed**: ${{ steps.run-tests.outputs.tests-passed }}" >> $GITHUB_STEP_SUMMARY
        fi
        if [[ "${{ steps.upload-report.outputs.success }}" != "" ]]; then
          echo "- **Report Uploaded**: ${{ steps.upload-report.outputs.success }}" >> $GITHUB_STEP_SUMMARY
        fi
